 version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "Building your stuff"
       - run: sleep 25
   deploy:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "Deploying your stuff"
       - run: sleep 25
 workflows:
    version: 2
    build_and_deploy:
      jobs:
        - build
        - deploy     
